channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.9.5
  - jupyter =1.0
  - jupyterlab_code_formatter =1.4.10
  - numpy =1.21.2
  - pandas =1.3.5
  - pyarrow =6.0.1
  - statsmodels =0.13.1
  - scipy =1.7.3
  - scikit-learn =1.0.1
  - matplotlib =3.5.1
  - seaborn =0.11.2
  - mpl-scatter-density =0.7
  - adjusttext =0.7.3.1
  - pingouin =0.5.3
  - adjusttext =0.7.3.1
  - statannot =0.2.3
  - xlrd =2.0.1
  - statannotations =0.5.0
  - openpyxl =3.0.10 
name: ngs-tools-python